[package]
name = "aoc-2020-01"
version = "0.1.0"
authors = ["Paul Fariello <paul.fariello@synacktiv.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "^0.4"
flexi_logger = "^0.15"
